<?php

return [

    'wechat_js' => [
        'appid' => env('wechat_js.app_id'),
        'secret' => env('wechat_js.secret'),
        'mch_id' => env('wechat_js.mch_id'),
        'key' => env('wechat_js.key'),
        'cert_pem' => env('wechat_js.cert_pem'),
        'key_pem' => env('wechat_js.key_pem'),
        'payment_callback' => env('wechat_js.payment_callback'),
        'refund_callback' => env('wechat_js.refund_callback'),
    ],
    'wechat_app' => [
        'appid' => env('wechat_app.app_id'),
        'secret' => env('wechat_app.secret'),
        'mch_id' => env('wechat_app.mch_id'),
        'key' => env('wechat_app.key'),
        'cert_pem' => env('wechat_app.cert_pem'),
        'key_pem' => env('wechat_app.key_pem'),
        'payment_callback' => env('wechat_app.payment_callback'),
        'refund_callback' => env('wechat_app.refund_callback'),
    ],
    'wechat_mini' => [
        'appid' => env('wechat_mini.app_id'),
        'mch_id' => env('wechat_mini.mch_id'),
        'key' => env('wechat_mini.key'),
        'cert_pem' => env('wechat_mini.cert_pem'),
        'key_pem' => env('wechat_mini.key_pem'),
        'payment_callback' => env('wechat_mini.payment_callback'),
        'refund_callback' => env('wechat_mini.refund_callback'),
    ],
    'wechat_mweb' => [
        'appid' => env('wechat_mweb.app_id'),
        'secret' => env('wechat_mweb.secret'),
        'mch_id' => env('wechat_mweb.mch_id'),
        'key' => env('wechat_mweb.key'),
        'cert_pem' => env('wechat_mweb.cert_pem'),
        'key_pem' => env('wechat_mweb.key_pem'),
        'payment_callback' => env('wechat_mweb.payment_callback'),
        'refund_callback' => env('wechat_mweb.refund_callback'),
    ],
    'wechat_qr' => [
        'appid' => env('wechat_qr.app_id'),
        'secret' => env('wechat_qr.secret'),
        'mch_id' => env('wechat_qr.mch_id'),
        'key' => env('wechat_qr.key'),
        'cert_pem' => env('wechat_qr.cert_pem'),
        'key_pem' => env('wechat_qr.key_pem'),
        'payment_callback' => env('wechat_qr.payment_callback'),
        'refund_callback' => env('wechat_qr.refund_callback'),
    ],

    'alipay' => [
        'app_id' => env('alipay_payment.app_id'),
        'aes' => env('alipay_payment.aes'),
        'private_key' => env('alipay_payment.private_key'),
        'public_key' => env('alipay_payment.public_key'),
        'payment_callback' => env('alipay_payment.payment_callback'),
        'refund_callback' => env('alipay_payment.refund_callback'),
    ],
    'alipay_app' => [
        'app_id' => env('alipay_app.app_id'),
        'aes' => env('alipay_app.aes'),
        'private_key' => env('alipay_app.private_key'),
        'public_key' => env('alipay_app.public_key'),
        'payment_callback' => env('alipay_app.payment_callback'),
        'refund_callback' => env('alipay_app.refund_callback'),
    ],
    'alipay_scan' => [
        'app_id' => env('alipay_scan.app_id'),
        'aes' => env('alipay_scan.aes'),
        'private_key' => env('alipay_scan.private_key'),
        'public_key' => env('alipay_scan.public_key'),
        'payment_callback' => env('alipay_scan.payment_callback'),
        'refund_callback' => env('alipay_scan.refund_callback'),
    ],
];
